openapi: 3.0.0
info:
  title: messages
  version: '1.0'
servers:
  - url: 'http://localhost:3000/v1/chatting_messages'
    description: local
paths:
  '/history/:user_id':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_name:
                      type: string
                    user_type:
                      type: string
                    message:
                      type: string
      operationId: get-all
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      description: ''
    parameters: []
  /send:
    post:
      summary: ''
      operationId: post-reply
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  return_message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                user_id:
                  type: string
    parameters: []
components:
  schemas: {}
