openapi: 3.0.0
info:
  title: robotgirls
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/v1/robot_girls'
    description: local
paths:
  /reply:
    post:
      summary: ''
      operationId: post-v1-robot_girls-reply
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  return_message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
    parameters: []
components:
  schemas: {}
